const DB_NAME = "keepmyreceipt-db";
const DB_VERSION = 1;
const STORE = "purchases";
const state = { purchases: [], view: "home", filter: "all", query: "", editingId: null, receiptBlob: null, receiptName: "", receiptType: "" };
const $ = (id) => document.getElementById(id);
const els = { homeView: $("homeView"), receiptsView: $("receiptsView"), settingsView: $("settingsView"), recentList: $("recentList"), receiptList: $("receiptList"), searchInput: $("searchInput"), filterChips: $("filterChips"), savedCount: $("savedCount"), returnsCount: $("returnsCount"), warrantyCount: $("warrantyCount"), dialog: $("purchaseDialog"), form: $("purchaseForm"), formTitle: $("formTitle"), closeDialog: $("closeDialog"), deleteBtn: $("deleteBtn"), saveBtn: $("saveBtn"), receiptInput: $("receiptInput"), receiptLabel: $("receiptLabel"), receiptPreview: $("receiptPreview"), itemName: $("itemName"), retailer: $("retailer"), category: $("category"), currency: $("currency"), amount: $("amount"), purchaseDate: $("purchaseDate"), returnDays: $("returnDays"), warrantyMonths: $("warrantyMonths"), serialNumber: $("serialNumber"), notes: $("notes"), returnHint: $("returnHint"), warrantyHint: $("warrantyHint"), backupBtn: $("backupBtn"), restoreInput: $("restoreInput"), toast: $("toast"), settingsShortcut: $("settingsShortcut") };
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function getAllPurchases(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly");const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function putPurchase(purchase){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(purchase);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function removePurchase(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function replaceAllPurchases(records){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");const store=tx.objectStore(STORE);store.clear();for(const record of records)store.put(record);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function addDays(dateString,days){if(!dateString||!Number(days))return null;const d=new Date(`${dateString}T12:00:00`);d.setDate(d.getDate()+Number(days));return d}
function addMonths(dateString,months){if(!dateString||!Number(months))return null;const d=new Date(`${dateString}T12:00:00`);d.setMonth(d.getMonth()+Number(months));return d}
function daysFromNow(date){if(!date)return null;const now=new Date();now.setHours(0,0,0,0);const target=new Date(date);target.setHours(0,0,0,0);return Math.ceil((target-now)/86400000)}
function formatDate(date){if(!date)return"—";return new Intl.DateTimeFormat("en-NZ",{day:"numeric",month:"short",year:"numeric"}).format(new Date(date))}
function formatMoney(value,currency="NZD"){if(value===""||value===null||value===undefined)return"";const n=Number(value);if(!Number.isFinite(n))return"";return new Intl.NumberFormat("en-NZ",{style:"currency",currency,maximumFractionDigits:2}).format(n)}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function getBadges(p){const badges=[];const r=daysFromNow(addDays(p.purchaseDate,p.returnDays));const w=daysFromNow(addMonths(p.purchaseDate,p.warrantyMonths));if(r!==null&&r>=0&&r<=14)badges.push({cls:"urgent",text:r===0?"Return today":`Return ${r}d`});else if(r!==null&&r>=0&&r<=30)badges.push({cls:"warn",text:`Return ${r}d`});if(w!==null&&w>=0&&w<=60)badges.push({cls:"warn",text:w===0?"Warranty today":`Warranty ${w}d`});else if(w!==null&&w>=0)badges.push({cls:"good",text:"Under warranty"});else if(w!==null&&w<0)badges.push({cls:"",text:"Warranty expired"});if(!badges.length)badges.push({cls:"",text:formatDate(p.purchaseDate)});return badges.slice(0,2)}
function matchesFilter(p,filter){const r=daysFromNow(addDays(p.purchaseDate,p.returnDays));const w=daysFromNow(addMonths(p.purchaseDate,p.warrantyMonths));if(filter==="returns")return r!==null&&r>=0&&r<=30;if(filter==="warranties")return w!==null&&w>=0&&w<=90;if(filter==="expired")return w!==null&&w<0;return true}
function thumbHtml(p){if(p.receiptBlob&&p.receiptType?.startsWith("image/")){const url=URL.createObjectURL(p.receiptBlob);setTimeout(()=>URL.revokeObjectURL(url),60000);return `<div class="thumb"><img src="${url}" alt=""></div>`}if(p.receiptBlob&&p.receiptType==="application/pdf")return `<div class="thumb">PDF</div>`;return `<div class="thumb">▤</div>`}
function cardHtml(p){const badges=getBadges(p).map(b=>`<span class="pill ${b.cls}">${escapeHtml(b.text)}</span>`).join("");return `<article class="purchase-card" data-id="${p.id}" role="button" tabindex="0">${thumbHtml(p)}<div class="card-main"><div class="card-top"><div class="card-title"><h3>${escapeHtml(p.itemName)}</h3><p>${escapeHtml(p.retailer||p.category||"Purchase")}</p></div><span class="price">${escapeHtml(formatMoney(p.amount,p.currency))}</span></div><div class="card-meta">${badges}</div></div></article>`}
function emptyHtml(title,copy){return `<div class="empty"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(copy)}</p></div>`}
function render(){const sorted=[...state.purchases].sort((a,b)=>new Date(b.purchaseDate)-new Date(a.purchaseDate));els.savedCount.textContent=sorted.length;els.returnsCount.textContent=sorted.filter(p=>matchesFilter(p,"returns")).length;els.warrantyCount.textContent=sorted.filter(p=>matchesFilter(p,"warranties")).length;els.recentList.innerHTML=sorted.length?sorted.slice(0,4).map(cardHtml).join(""):emptyHtml("No receipts yet","Add your first purchase and KeepMyReceipt will track its return and warranty dates.");const q=state.query.trim().toLowerCase();const filtered=sorted.filter(p=>{const searchable=[p.itemName,p.retailer,p.category,p.serialNumber].filter(Boolean).join(" ").toLowerCase();return(!q||searchable.includes(q))&&matchesFilter(p,state.filter)});els.receiptList.innerHTML=filtered.length?filtered.map(cardHtml).join(""):emptyHtml(sorted.length?"No matching receipts":"No receipts yet",sorted.length?"Try another search or filter.":"Tap + to save your first receipt.");document.querySelectorAll(".purchase-card").forEach(card=>{const open=()=>openEditor(card.dataset.id);card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")open()})})}
function navigate(view){state.view=view;document.querySelectorAll(".view").forEach(el=>el.classList.toggle("active",el.dataset.view===view));document.querySelectorAll(".nav-item").forEach(el=>el.classList.toggle("active",el.dataset.nav===view));window.scrollTo({top:0,behavior:"smooth"})}
function setFilter(filter){state.filter=filter;document.querySelectorAll(".chip").forEach(chip=>chip.classList.toggle("active",chip.dataset.filter===filter));navigate("receipts");render()}
function todayString(){return new Date().toISOString().slice(0,10)}
function resetForm(){state.editingId=null;state.receiptBlob=null;state.receiptName="";state.receiptType="";els.form.reset();els.purchaseDate.value=todayString();els.returnDays.value="30";els.warrantyMonths.value="12";els.category.value="Electronics";els.currency.value="NZD";els.receiptLabel.textContent="Take photo or choose receipt";els.receiptPreview.innerHTML="";els.receiptPreview.classList.add("hidden");els.formTitle.textContent="Add receipt";els.deleteBtn.classList.add("hidden");els.saveBtn.textContent="Save purchase";updateDateHints()}
function fillForm(p){state.editingId=p.id;state.receiptBlob=p.receiptBlob||null;state.receiptName=p.receiptName||"";state.receiptType=p.receiptType||"";els.itemName.value=p.itemName||"";els.retailer.value=p.retailer||"";els.category.value=p.category||"Electronics";els.currency.value=p.currency||"NZD";els.amount.value=p.amount??"";els.purchaseDate.value=p.purchaseDate||todayString();els.returnDays.value=p.returnDays??0;els.warrantyMonths.value=p.warrantyMonths??0;els.serialNumber.value=p.serialNumber||"";els.notes.value=p.notes||"";els.receiptLabel.textContent=p.receiptName||"Take photo or choose receipt";showReceiptPreview();els.formTitle.textContent="Purchase details";els.deleteBtn.classList.remove("hidden");els.saveBtn.textContent="Save changes";updateDateHints()}
function openNew(){resetForm();els.dialog.showModal()}
function openEditor(id){const p=state.purchases.find(x=>x.id===id);if(!p)return;fillForm(p);els.dialog.showModal()}
function closeDialog(){if(els.dialog.open)els.dialog.close()}
function updateDateHints(){const purchaseDate=els.purchaseDate.value;const returnDate=addDays(purchaseDate,els.returnDays.value);const warrantyDate=addMonths(purchaseDate,els.warrantyMonths.value);els.returnHint.textContent=returnDate?`Return by ${formatDate(returnDate)}`:"No return reminder";els.warrantyHint.textContent=warrantyDate?`Until ${formatDate(warrantyDate)}`:"No warranty reminder"}
function showReceiptPreview(){els.receiptPreview.innerHTML="";if(!state.receiptBlob){els.receiptPreview.classList.add("hidden");return}els.receiptPreview.classList.remove("hidden");if(state.receiptType?.startsWith("image/")){const url=URL.createObjectURL(state.receiptBlob);const img=document.createElement("img");img.src=url;img.alt="Receipt preview";img.onload=()=>URL.revokeObjectURL(url);els.receiptPreview.appendChild(img)}else{els.receiptPreview.innerHTML=`<div class="pdf-preview">PDF · ${escapeHtml(state.receiptName)}</div>`}}
function showToast(message){els.toast.textContent=message;els.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.remove("show"),2200)}
async function refresh(){state.purchases=await getAllPurchases();render()}
async function saveForm(event){event.preventDefault();if(!els.itemName.value.trim()||!els.purchaseDate.value)return;const old=state.purchases.find(x=>x.id===state.editingId);const wasEditing=Boolean(state.editingId);const record={id:state.editingId||crypto.randomUUID(),itemName:els.itemName.value.trim(),retailer:els.retailer.value.trim(),category:els.category.value,currency:els.currency.value,amount:els.amount.value===""?"":Number(els.amount.value),purchaseDate:els.purchaseDate.value,returnDays:Number(els.returnDays.value)||0,warrantyMonths:Number(els.warrantyMonths.value)||0,serialNumber:els.serialNumber.value.trim(),notes:els.notes.value.trim(),receiptBlob:state.receiptBlob,receiptName:state.receiptName,receiptType:state.receiptType,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};await putPurchase(record);await refresh();closeDialog();showToast(wasEditing?"Purchase updated":"Receipt saved")}
function fileToBase64(blob){return new Promise((resolve,reject)=>{if(!blob)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
function base64ToBlob(dataUrl){if(!dataUrl)return null;const[meta,data]=dataUrl.split(",");const mime=meta.match(/data:(.*?);base64/)?.[1]||"application/octet-stream";const binary=atob(data);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime})}
async function exportBackup(){try{const records=[];for(const p of state.purchases)records.push({...p,receiptBlob:await fileToBase64(p.receiptBlob)});const payload={app:"KeepMyReceipt",version:1,exportedAt:new Date().toISOString(),purchases:records};const blob=new Blob([JSON.stringify(payload)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`keepmyreceipt-backup-${todayString()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Backup exported")}catch(error){console.error(error);showToast("Backup failed")}}
async function importBackup(file){try{const payload=JSON.parse(await file.text());if(payload?.app!=="KeepMyReceipt"||!Array.isArray(payload.purchases))throw new Error("Invalid backup");if(!confirm(`Restore ${payload.purchases.length} purchases? This replaces the data currently on this device.`))return;const records=payload.purchases.map(p=>({...p,receiptBlob:typeof p.receiptBlob==="string"?base64ToBlob(p.receiptBlob):null}));await replaceAllPurchases(records);await refresh();showToast("Backup restored");navigate("home")}catch(error){console.error(error);showToast("Could not restore backup")}finally{els.restoreInput.value=""}}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-nav]");if(nav)navigate(nav.dataset.nav);const add=e.target.closest("[data-action='add']");if(add)openNew();const filterTarget=e.target.closest("[data-filter-target]");if(filterTarget)setFilter(filterTarget.dataset.filterTarget)});els.settingsShortcut.addEventListener("click",()=>navigate("settings"));els.filterChips.addEventListener("click",e=>{const chip=e.target.closest("[data-filter]");if(chip)setFilter(chip.dataset.filter)});els.searchInput.addEventListener("input",()=>{state.query=els.searchInput.value;render()});els.closeDialog.addEventListener("click",closeDialog);els.form.addEventListener("submit",saveForm);els.purchaseDate.addEventListener("change",updateDateHints);els.returnDays.addEventListener("input",updateDateHints);els.warrantyMonths.addEventListener("input",updateDateHints);els.receiptInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;state.receiptBlob=file;state.receiptName=file.name;state.receiptType=file.type;els.receiptLabel.textContent=file.name;showReceiptPreview()});els.deleteBtn.addEventListener("click",async()=>{if(!state.editingId)return;const p=state.purchases.find(x=>x.id===state.editingId);if(!confirm(`Delete “${p?.itemName||"this purchase"}”?`))return;await removePurchase(state.editingId);await refresh();closeDialog();showToast("Purchase deleted")});els.backupBtn.addEventListener("click",exportBackup);els.restoreInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(file)importBackup(file)});els.dialog.addEventListener("click",e=>{const rect=els.dialog.getBoundingClientRect();const outside=e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom;if(outside)closeDialog()});if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));refresh().catch(error=>{console.error(error);els.recentList.innerHTML=emptyHtml("Could not open local storage","Try reloading the page.");els.receiptList.innerHTML=els.recentList.innerHTML});